favicon: null
name: playlist
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9178542895242572
  brandStrength: 0.5884323783684522
  rhythmicContrast: 0.9473950124811381
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.4842627791222185
typography_spectrum: 0.7174326663371176
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.7365592
analytics:
  twitter: null
  google: null
  facebook: null
